### ISSUE TITLE
TextField labelText/hintText ignores value

### ISSUE THREAD

**Issue by earlin** [bobril/bobril-m#5]
A text field with a value looks normal when you focus it.

![TextField focused](https://user-images.githubusercontent.com/47703302/58386871-7cdbb780-7ff5-11e9-8ca7-19deeb5ea395.png)

Once blurred, text field hint prevails and looks awful.

![TextField issue](https://user-images.githubusercontent.com/47703302/58386872-7d744e00-7ff5-11e9-8595-dc5c6429251d.png)

**Comment by earlin** [comment]
My guess is something to do with [textField.ts at line 181](https://github.com/bobril/bobril-m/blob/master/src/textField.ts#L181) and [textField.ts at line 151](https://github.com/bobril/bobril-m/blob/master/src/textField.ts#L151)

**Comment by earlin** [comment]
I tried to fix it myself but could not, this fails when the passed value is string value, but when I switch to using IProp<string>, it works.

**Comment by Bobris** [comment]
Small example code to reproduce would help.

**Comment by earlin** [comment]
I investigated further, my solution was to use IProp, the issue is that the value when is a string and passed to underlying input is not updated in component
So the length check in isValid fails

Reproduce:
Make a TextField give it a string not IProp value, and a labelText.

Youness BELFKIH

________________________________
